version: '3.8'
services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: express
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql-init-scripts:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        expose:
            - 80
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql

    backend:
        build: .
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=DEVELOPMENT
        depends_on:
            - mysql
        volumes:
            - .:/usr/src/app # Sincroniza el directorio local con el directorio en el contenedor
            - /usr/src/app/node_modules

volumes:
    mysql-data:
