const mesaRoutes = require('./mesaRoutes')
const empleadoRoutes = require('./empleadoRoutes')
const clienteRoutes = require('./clienteRoutes')
const categoriaRoutes = require('./categoriaRoutes')
const cajaRoutes = require('./cajaRoutes')
const grupoRoutes = require('./grupoRoutes')
const itemInventarioRoutes = require('./itemInventarioRoutes')
const itemMenuRoutes = require('./itemMenuRoutes')
const ordenRoutes = require('./ordenRoutes')
const movimientoRoutes = require('./movimientoRoutes')
const pagoRoutes = require('./pagoRoutes')
const compraRoutes = require('./compraRoutes')
const logRoutes = require('./logRoutes')
module.exports = (app) => {
    app.use('/api', mesaRoutes)
    app.use('/api', empleadoRoutes)
    app.use('/api', clienteRoutes)
    app.use('/api', categoriaRoutes)
    app.use('/api', cajaRoutes)
    app.use('/api', grupoRoutes)
    app.use('/api', itemInventarioRoutes)
    app.use('/api', itemMenuRoutes)
    app.use('/api', ordenRoutes)
    app.use('/api', movimientoRoutes)
    app.use('/api', pagoRoutes)
    app.use('/api', compraRoutes)
    app.use('/api', logRoutes)
}
